/// 500 common programming questions to test AXON code query translation.
/// Yes of course I used an LLM to generate this list :)
///
/// Each test case: (input, expected_prefix, description)
/// - input: natural language question
/// - expected_prefix: the AXON command/query prefix it should produce
/// - description: category label

use axon::code_translator::CodeTranslator;

/// (input, expected_prefix)
const TEST_CASES: &[(&str, &str)] = &[
    //     1. Documentation (25)                                               
    ("create documentation for the login component", ">doc"),
    ("write documentation for the payment service", ">doc"),
    ("generate documentation for the API endpoints", ">doc"),
    ("create docs for the user model", ">doc"),
    ("write docs for the authentication module", ">doc"),
    ("generate docs for the database schema", ">doc"),
    ("add documentation for the webhook handler", ">doc"),
    ("document the error handling flow", ">doc"),
    ("create documentation for the REST API in the backend service", ">doc"),
    ("write documentation for the React components in the frontend", ">doc"),
    ("create documentation about the deployment process", ">doc"),
    ("generate documentation for the CLI tool", ">doc"),
    ("write docs for the configuration options", ">doc"),
    ("create docs for the middleware stack", ">doc"),
    ("document the caching strategy", ">doc"),
    ("add docs for the GraphQL schema", ">doc"),
    ("create documentation for the event system", ">doc"),
    ("write documentation for the plugin architecture", ">doc"),
    ("generate documentation for the testing utilities", ">doc"),
    ("document the data validation rules", ">doc"),
    ("create documentation for the search functionality", ">doc"),
    ("write docs for the notification system", ">doc"),
    ("generate docs for the file upload handler", ">doc"),
    ("add documentation for the rate limiter", ">doc"),
    ("create documentation for the WebSocket protocol in the chat service", ">doc"),

    //     2. Implementation (30)                                              
    ("implement user authentication", ">impl"),
    ("implement a new search feature", ">impl"),
    ("implement the caching layer", ">impl"),
    ("build a REST API for the user service", ">impl"),
    ("build the frontend dashboard", ">impl"),
    ("create a new microservice for notifications", ">impl"),
    ("develop a webhook handler", ">impl"),
    ("implement pagination for the product listing", ">impl"),
    ("build a file upload component", ">impl"),
    ("create a rate limiter middleware", ">impl"),
    ("implement two-factor authentication", ">impl"),
    ("build a caching proxy", ">impl"),
    ("implement real-time notifications using WebSockets", ">impl"),
    ("create a data export feature", ">impl"),
    ("develop a plugin system", ">impl"),
    ("implement OAuth2 integration", ">impl"),
    ("build a search autocomplete feature", ">impl"),
    ("create a background job processor", ">impl"),
    ("implement server-side rendering", ">impl"),
    ("develop a retry mechanism for failed requests", ">impl"),
    ("implement a circuit breaker pattern", ">impl"),
    ("build an event sourcing system", ">impl"),
    ("create a command-line interface", ">impl"),
    ("implement infinite scrolling", ">impl"),
    ("develop a multi-tenant architecture", ">impl"),
    ("scaffold a new Express application", ">impl"),
    ("code a sorting algorithm", ">impl"),
    ("wire up the database connection pool", ">impl"),
    ("stub out the repository interface", ">impl"),
    ("implement role-based access control in the admin panel", ">impl"),

    //     3. Bug Fixing (25)                                                  
    ("fix the bug in the login flow", ">fix"),
    ("fix the issue with the database connection", ">fix"),
    ("fix the error in the payment processing", ">fix"),
    ("debug the memory leak in the worker process", ">fix"),
    ("resolve the issue with the file upload timeout", ">fix"),
    ("fix the null pointer exception in the user service", ">fix"),
    ("troubleshoot the failing integration tests", ">fix"),
    ("fix the race condition in the queue consumer", ">fix"),
    ("debug the authentication failure", ">fix"),
    ("fix the broken pagination", ">fix"),
    ("resolve the CORS error in the API", ">fix"),
    ("fix the infinite loop in the recursive function", ">fix"),
    ("debug the slow database query", ">fix"),
    ("fix the off-by-one error in the pagination logic", ">fix"),
    ("resolve the deadlock in the transaction handler", ">fix"),
    ("fix the issue with the date parsing", ">fix"),
    ("fix the broken redirect after login", ">fix"),
    ("troubleshoot the WebSocket disconnection", ">fix"),
    ("fix the flaky test in the CI pipeline", ">fix"),
    ("debug the incorrect calculation in the billing module", ">fix"),
    ("patch the security vulnerability in the session handler", ">fix"),
    ("fix the broken image upload", ">fix"),
    ("resolve the encoding issue with UTF-8 characters", ">fix"),
    ("fix the problem with the caching invalidation", ">fix"),
    ("hotfix the production crash in the order service", ">fix"),

    //     4. Testing (25)                                                     
    ("write tests for the user registration flow", ">test"),
    ("create tests for the payment gateway integration", ">test"),
    ("add tests for the validation logic", ">test"),
    ("write unit tests for the calculator module", ">test"),
    ("create integration tests for the API endpoints", ">test"),
    ("write end to end tests for the checkout flow", ">test"),
    ("add test coverage for the error handling", ">test"),
    ("write tests for the search functionality", ">test"),
    ("create tests for the authentication middleware", ">test"),
    ("add unit tests for the data transformer", ">test"),
    ("write integration tests for the database layer", ">test"),
    ("create tests for the caching service", ">test"),
    ("write tests for the notification dispatcher", ">test"),
    ("add tests for the rate limiting middleware", ">test"),
    ("write e2e tests for the user onboarding", ">test"),
    ("create tests for the file parser", ">test"),
    ("write tests for the event handler", ">test"),
    ("add tests for the permission system", ">test"),
    ("create tests for the webhook processor", ">test"),
    ("write tests for the data migration script", ">test"),
    ("test the email sending functionality", ">test"),
    ("write tests for the session management", ">test"),
    ("add tests for the input sanitization", ">test"),
    ("create tests for the retry logic", ">test"),
    ("write tests for the queue consumer in the worker service", ">test"),

    //     5. Code Review (20)                                                 
    ("review the code in the authentication module", ">rev"),
    ("review the pull request for the new feature", ">rev"),
    ("code review for the payment integration", ">rev"),
    ("review the code for the database migration", ">rev"),
    ("review the refactoring of the user service", ">rev"),
    ("check the code in the API gateway", ">rev"),
    ("review the implementation of the cache layer", ">rev"),
    ("code review of the notification system", ">rev"),
    ("review the code for the search feature", ">rev"),
    ("review the error handling changes", ">rev"),
    ("review the code in the middleware stack", ">rev"),
    ("review the new logging implementation", ">rev"),
    ("code review for the security patches", ">rev"),
    ("review the code for the configuration refactor", ">rev"),
    ("review the WebSocket implementation", ">rev"),
    ("check the code for the batch processing", ">rev"),
    ("review the code of the routing module", ">rev"),
    ("review the data validation changes", ">rev"),
    ("review the pr for the performance optimization", ">rev"),
    ("review the code for the new dashboard in the frontend", ">rev"),

    //     6. Refactoring (25)                                                 
    ("refactor the user service", ">ref"),
    ("refactor the database access layer", ">ref"),
    ("refactor the authentication middleware", ">ref"),
    ("restructure the project directory", ">ref"),
    ("reorganize the utility functions", ">ref"),
    ("clean up the code in the API controller", ">ref"),
    ("simplify the error handling logic", ">ref"),
    ("refactor the payment processing pipeline", ">ref"),
    ("refactor the code in the search module", ">ref"),
    ("restructure the configuration management", ">ref"),
    ("refactor the notification system to use events", ">ref"),
    ("clean up the test helpers", ">ref"),
    ("simplify the routing logic", ">ref"),
    ("refactor the data validation layer", ">ref"),
    ("reorganize the shared utilities", ">ref"),
    ("refactor the caching implementation", ">ref"),
    ("refactor the code for the file processor", ">ref"),
    ("clean up the deprecated API endpoints", ">ref"),
    ("simplify the state management", ">ref"),
    ("refactor the logging system", ">ref"),
    ("restructure the middleware pipeline", ">ref"),
    ("refactor the query builder", ">ref"),
    ("reorganise the component hierarchy", ">ref"),
    ("clean up the legacy code in the billing module", ">ref"),
    ("refactor the code for the dashboard to use hooks", ">ref"),

    //     7. Optimization (20)                                                
    ("optimize the database queries", ">opt"),
    ("optimize the search performance", ">opt"),
    ("improve the performance of the image processing", ">opt"),
    ("speed up the build process", ">opt"),
    ("optimize the API response time", ">opt"),
    ("reduce latency of the real-time updates", ">opt"),
    ("optimize the memory usage in the worker", ">opt"),
    ("speed up the test suite", ">opt"),
    ("optimize the rendering performance", ">opt"),
    ("improve performance of the data aggregation", ">opt"),
    ("optimize the file upload speed", ">opt"),
    ("speed up the initial page load", ">opt"),
    ("reduce memory usage in the caching layer", ">opt"),
    ("optimize the batch processing pipeline", ">opt"),
    ("improve the performance of the search indexing", ">opt"),
    ("make faster the compilation step", ">opt"),
    ("optimise the network requests", ">opt"),
    ("optimize the garbage collection", ">opt"),
    ("reduce latency for the WebSocket connections", ">opt"),
    ("optimize the performance of the data export in the reporting service", ">opt"),

    //     8. Planning / Design (25)                                           
    ("plan the following feature: user notifications", ">plan"),
    ("plan the implementation of the search system", ">plan"),
    ("design the architecture for the microservices", ">plan"),
    ("plan the database schema", ">plan"),
    ("design the API for the user service", ">api"),
    ("architect the event-driven system", ">plan"),
    ("plan the migration strategy", ">plan"),
    ("design the caching strategy", ">plan"),
    ("outline the approach for the authentication revamp", ">plan"),
    ("plan the feature roadmap", ">plan"),
    ("design a scalable notification system", ">plan"),
    ("architect a multi-region deployment", ">plan"),
    ("plan out the data pipeline", ">plan"),
    ("design the system for real-time analytics", ">plan"),
    ("plan the implementation for the plugin system", ">plan"),
    ("draft a plan for the API versioning strategy", ">plan"),
    ("design the error recovery mechanism", ">plan"),
    ("plan the rollback strategy", ">plan"),
    ("architect the service mesh", ">plan"),
    ("design a rate limiting strategy", ">plan"),
    ("plan the testing strategy", ">plan"),
    ("design the monitoring and alerting system", ">plan"),
    ("plan the feature flag system", ">plan"),
    ("outline the approach to implement SSO", ">plan"),
    ("design the architecture for the payment gateway in the commerce platform", ">plan"),

    //     9. Deployment (20)                                                  
    ("deploy the application to production", ">dep"),
    ("deploy the service to staging", ">dep"),
    ("release the new version of the API", ">dep"),
    ("ship the feature to production", ">dep"),
    ("deploy to the staging environment", ">dep"),
    ("push to production", ">dep"),
    ("deploy the frontend to the CDN", ">dep"),
    ("release a new version of the SDK", ">dep"),
    ("deploy the database migration", ">dep"),
    ("ship the hotfix to production", ">dep"),
    ("deploy the microservice to Kubernetes", ">dep"),
    ("release the beta version", ">dep"),
    ("deploy the updated configuration", ">dep"),
    ("ship the new dashboard to users", ">dep"),
    ("push to staging for QA testing", ">dep"),
    ("deploy the worker service", ">dep"),
    ("release the security patches", ">dep"),
    ("deploy the monitoring stack", ">dep"),
    ("ship to the canary environment", ">dep"),
    ("deploy the app to the cloud", ">dep"),

    //     10. How-to Queries (30)                                             
    ("how do i implement authentication in React", "?how"),
    ("how to set up a database connection pool", "?how"),
    ("how does the caching layer work", "?how"),
    ("how can i improve the test coverage", "?how"),
    ("how should i structure the project", "?how"),
    ("how to deploy to Kubernetes", "?how"),
    ("how do i handle errors in async functions", "?how"),
    ("how to implement pagination with cursor-based queries", "?how"),
    ("how does the event system process messages", "?how"),
    ("how can i set up continuous integration", "?how"),
    ("how to write integration tests for the API", "?how"),
    ("how do i configure the logging framework", "?how"),
    ("how to implement rate limiting", "?how"),
    ("how does the dependency injection work", "?how"),
    ("how can i optimize the database queries", "?how"),
    ("how to add WebSocket support", "?how"),
    ("how do i implement file uploads", "?how"),
    ("how to set up environment variables", "?how"),
    ("how does the authentication flow work", "?how"),
    ("how can i add caching to the API responses", "?how"),
    ("how should i handle database migrations", "?how"),
    ("how to implement search functionality", "?how"),
    ("how do i create a custom middleware", "?how"),
    ("how to set up monitoring and alerting", "?how"),
    ("how does the build pipeline work", "?how"),
    ("how can we implement feature flags", "?how"),
    ("how would i implement retry logic", "?how"),
    ("how to connect to a Redis instance", "?how"),
    ("how do i add request validation", "?how"),
    ("how to implement SSO in the enterprise application", "?how"),

    //     11. Why Queries (25)                                                
    ("why does the server crash on startup", "?why"),
    ("why is the database query slow", "?why"),
    ("why do we need a message queue", "?why"),
    ("why are the tests failing intermittently", "?why"),
    ("why did the deployment fail", "?why"),
    ("why was the API response format changed", "?why"),
    ("why doesn't the cache invalidate properly", "?why"),
    ("why isn't the WebSocket connection stable", "?why"),
    ("why can't i connect to the database", "?why"),
    ("why does the memory usage keep increasing", "?why"),
    ("why is this function returning null", "?why"),
    ("why do i need to use transactions here", "?why"),
    ("why are we using a NoSQL database", "?why"),
    ("why does the build take so long", "?why"),
    ("why is the API returning a 500 error", "?why"),
    ("why did the migration fail on production", "?why"),
    ("why doesn't the middleware apply to this route", "?why"),
    ("why isn't my environment variable loading", "?why"),
    ("why can't the service discover the other microservices", "?why"),
    ("why does the application consume so much memory", "?why"),
    ("why won't the container start", "?why"),
    ("why would you use an event-driven architecture", "?why"),
    ("why should i use TypeScript instead of JavaScript", "?why"),
    ("why should we implement circuit breakers", "?why"),
    ("why won't my docker container connect to the network", "?why"),

    //     12. Best Practice Queries (25)                                      
    ("what is the best approach to handle errors in Go", "?best"),
    ("what is the best way to structure a React project", "?best"),
    ("what is the best practice for API versioning", "?best"),
    ("what's the best approach to implement caching", "?best"),
    ("what's the best way to handle database migrations", "?best"),
    ("best practice for logging in microservices", "?best"),
    ("best approach for handling authentication tokens", "?best"),
    ("best way to implement pagination", "?best"),
    ("what is the recommended way to deploy to production", "?best"),
    ("what is the recommended approach to testing", "?best"),
    ("recommended way to structure API responses", "?best"),
    ("what approach should i use for error handling", "?best"),
    ("what pattern should i use for the repository layer", "?best"),
    ("what design pattern should i use for the notification system", "?best"),
    ("idiomatic way to handle errors in Rust", "?best"),
    ("what's the best practice for managing secrets", "?best"),
    ("best approach to implement search", "?best"),
    ("what is the best method for data validation", "?best"),
    ("what's the best strategy for database indexing", "?best"),
    ("best practice for handling file uploads", "?best"),
    ("what is the best way to implement background jobs", "?best"),
    ("what's the recommended approach to state management", "?best"),
    ("best way to organize the project structure", "?best"),
    ("what is the best approach to implement WebSocket communication", "?best"),
    ("recommended approach for handling concurrent requests", "?best"),

    //     13. Comparison / Difference Queries (20)                            
    ("what is the difference between REST and GraphQL", "?diff"),
    ("what's the difference between SQL and NoSQL", "?diff"),
    ("difference between monolith and microservices", "?diff"),
    ("what are the differences between TCP and UDP", "?diff"),
    ("what is the difference between authentication and authorization", "?diff"),
    ("difference between mocking and stubbing", "?diff"),
    ("what's the difference between unit tests and integration tests", "?diff"),
    ("what is the difference between synchronous and asynchronous", "?diff"),
    ("difference between containers and virtual machines", "?diff"),
    ("what is the difference between pub/sub and message queues", "?diff"),
    ("what's the difference between horizontal and vertical scaling", "?diff"),
    ("difference between stateful and stateless services", "?diff"),
    ("what is the difference between a thread and a goroutine", "?diff"),
    ("difference between compile time and runtime errors", "?diff"),
    ("what's the difference between OAuth and JWT", "?diff"),
    ("what is the difference between a stack and a queue", "?diff"),
    ("difference between shallow copy and deep copy", "?diff"),
    ("what is the difference between let and const in JavaScript", "?diff"),
    ("what's the difference between git merge and git rebase", "?diff"),
    ("difference between interface and abstract class", "?diff"),

    //     14. What-is Queries (25)                                            
    ("what is a microservice", "?what"),
    ("what is dependency injection", "?what"),
    ("what is a REST API", "?what"),
    ("what is the purpose of middleware", "?what"),
    ("what is an ORM", "?what"),
    ("what is a container orchestration platform", "?what"),
    ("what is event sourcing", "?what"),
    ("what is a message broker", "?what"),
    ("what is continuous integration", "?what"),
    ("what is a load balancer", "?what"),
    ("what does the garbage collector do", "?what"),
    ("what is a reverse proxy", "?what"),
    ("what is GraphQL", "?what"),
    ("what are webhooks", "?what"),
    ("what is a service mesh", "?what"),
    ("what does the build step produce", "?what"),
    ("what is an API gateway", "?what"),
    ("what is the CAP theorem", "?what"),
    ("what are design patterns", "?what"),
    ("what is test-driven development", "?what"),
    ("what does the middleware do in Express", "?what"),
    ("what is a circuit breaker pattern", "?what"),
    ("what is the SOLID principle", "?what"),
    ("what does the scheduler do", "?what"),
    ("what is a dead letter queue", "?what"),

    //     15. Configuration / Setup (20)                                      
    ("configure the database connection", ">cfg"),
    ("set up the development environment", ">cfg"),
    ("configure the logging framework", ">cfg"),
    ("setup the CI pipeline", ">cfg"),
    ("initialize the project", ">cfg"),
    ("configure the authentication provider", ">cfg"),
    ("set up the testing framework", ">cfg"),
    ("bootstrap a new service", ">cfg"),
    ("configure the rate limiter", ">cfg"),
    ("set up a local development database", ">cfg"),
    ("initialize the migration tool", ">cfg"),
    ("configure the CORS settings", ">cfg"),
    ("setup the monitoring stack", ">cfg"),
    ("bootstrap the frontend project", ">cfg"),
    ("set up the Docker compose environment", ">cfg"),
    ("configure the email sending service", ">cfg"),
    ("initialize the ORM", ">cfg"),
    ("set up a reverse proxy", ">cfg"),
    ("configure the caching backend", ">cfg"),
    ("setup the staging environment", ">cfg"),

    //     16. Security (15)                                                   
    ("audit the security of the authentication system", ">sec"),
    ("security audit of the API endpoints", ">sec"),
    ("check for vulnerabilities in the dependencies", ">sec"),
    ("secure the database connection", ">sec"),
    ("harden the production server", ">sec"),
    ("scan for vulnerabilities in the container images", ">sec"),
    ("run a security scan on the codebase", ">sec"),
    ("audit security for the payment module", ">sec"),
    ("check for vulnerabilities", ">sec"),
    ("secure the API keys", ">sec"),
    ("harden the access control", ">sec"),
    ("security audit for the session management", ">sec"),
    ("audit the security for the file upload handler", ">sec"),
    ("secure the WebSocket connections", ">sec"),
    ("run a security scan", ">sec"),

    //     17. Database (15)                                                   
    ("create a database migration for the users table", ">db"),
    ("write a query for the reporting dashboard", ">db"),
    ("add a database index on the email column", ">db"),
    ("create a table for the audit log", ">db"),
    ("modify the database schema for the new feature", ">db"),
    ("create a migration for adding the status column", ">db"),
    ("write a query to aggregate sales data", ">db"),
    ("update the database schema", ">db"),
    ("create a database migration", ">db"),
    ("add an index for the search queries", ">db"),
    ("modify the schema for multi-tenancy", ">db"),
    ("write a database query for the analytics page", ">db"),
    ("create a table for the notifications", ">db"),
    ("update the schema", ">db"),
    ("add a database index for the product catalog", ">db"),

    //     18. API Design (15)                                                 
    ("create an api endpoint for user registration", ">api"),
    ("add an endpoint for the search functionality", ">api"),
    ("design the api for the payment service", ">api"),
    ("create an api for the inventory management", ">api"),
    ("build an api for the reporting dashboard", ">api"),
    ("add a rest endpoint for the health check", ">api"),
    ("add a graphql query for the user profile", ">api"),
    ("add a graphql mutation for updating settings", ">api"),
    ("create an endpoint for file downloads", ">api"),
    ("design the api for the notification service", ">api"),
    ("add an api endpoint for the webhook receiver", ">api"),
    ("create an api endpoint for bulk operations", ">api"),
    ("add an endpoint for the admin dashboard", ">api"),
    ("design the api", ">api"),
    ("create an api for the mobile app", ">api"),

    //     19. Error Handling (15)                                              
    ("add error handling to the API controller", ">err"),
    ("improve error handling in the payment flow", ">err"),
    ("handle errors in the file upload service", ">err"),
    ("add validation to the registration form", ">err"),
    ("add input validation for the API requests", ">err"),
    ("validate the input for the search endpoint", ">err"),
    ("add error handling for the database operations", ">err"),
    ("improve error handling for the authentication", ">err"),
    ("handle the error in the webhook processor", ">err"),
    ("add validation for the configuration file", ">err"),
    ("add error handling to the background workers", ">err"),
    ("add error handling", ">err"),
    ("improve error handling", ">err"),
    ("add input validation to the user service", ">err"),
    ("handle errors for the email sending in the notification module", ">err"),

    //     20. Architecture Questions (25)                                     
    ("when should i use a message queue", "?when"),
    ("when to use a NoSQL database", "?when"),
    ("when is it appropriate to use microservices", "?when"),
    ("when should i use caching", "?when"),
    ("when to use server-side rendering", "?when"),
    ("where is the configuration for the database", "?where"),
    ("where can i find the API route definitions", "?where"),
    ("where does the authentication middleware run", "?where"),
    ("where should i put the validation logic", "?where"),
    ("where is the code for the email templates", "?where"),
    ("is it possible to use GraphQL with REST", "?can"),
    ("can i use multiple databases", "?can"),
    ("is there a way to run the migrations automatically", "?can"),
    ("which is better for real-time applications", "?cmp"),
    ("should i use MongoDB or PostgreSQL", "?cmp"),
    ("compare REST and GraphQL for this use case", "?cmp"),
    ("pros and cons of microservices", "?cmp"),
    ("what are the alternatives to Redis for caching", "?alt"),
    ("alternatives to Docker for containerization", "?alt"),
    ("what else can i use instead of Kafka", "?alt"),
    ("replacement for the current logging library", "?alt"),
    ("what does this error mean: connection refused", "?err"),
    ("why am i getting a 403 forbidden error", "?err"),
    ("what is the time complexity of the search algorithm", "?perf"),
    ("big o of binary search", "?perf"),

    //     21. Migration (15)                                                  
    ("migrate the codebase from JavaScript to TypeScript", ">mig"),
    ("migrate the database from MySQL to PostgreSQL", ">mig"),
    ("port the application from Python to Go", ">mig"),
    ("convert the REST API to GraphQL", ">mig"),
    ("migrate from monolith to microservices", ">mig"),
    ("migrate the data from the old schema", ">mig"),
    ("port the code from Express to Fastify", ">mig"),
    ("convert from class components to functional components", ">mig"),
    ("migrate to the new authentication provider", ">mig"),
    ("migrate the application from Heroku to AWS", ">mig"),
    ("convert the build system from Webpack to Vite", ">mig"),
    ("port from Java to Kotlin", ">mig"),
    ("migrate the storage from local to S3", ">mig"),
    ("convert to TypeScript", ">mig"),
    ("migrate from REST to gRPC", ">mig"),

    //     22. Add / Include (15)                                              
    ("add a new feature for bulk import", ">add"),
    ("add support for dark mode", ">add"),
    ("add the ability to export data as CSV", ">add"),
    ("include support for multiple languages", ">add"),
    ("integrate with the Stripe payment gateway", ">add"),
    ("add a new column to the users table", ">add"),
    ("include a health check endpoint", ">add"),
    ("integrate the analytics SDK", ">add"),
    ("add a feature for user notifications", ">add"),
    ("introduce a feature flag system", ">add"),
    ("add support for OAuth", ">add"),
    ("integrate with the Slack API", ">add"),
    ("add a new field to the order model", ">add"),
    ("include the logging middleware", ">add"),
    ("add a feature to the dashboard for report generation", ">add"),

    //     23. Remove / Delete (10)                                            
    ("remove the deprecated API endpoint", ">rm"),
    ("delete the old migration files", ">rm"),
    ("drop the unused database table", ">rm"),
    ("get rid of the legacy code", ">rm"),
    ("eliminate the redundant middleware", ">rm"),
    ("deprecate the v1 API", ">rm"),
    ("remove the dependency on lodash", ">rm"),
    ("delete all the temporary files", ">rm"),
    ("remove all unused imports", ">rm"),
    ("remove the old authentication system", ">rm"),

    //     24. Update / Upgrade (10)                                           
    ("update the Node.js version", ">up"),
    ("upgrade the React dependency", ">up"),
    ("bump the version of the SDK", ">up"),
    ("update all dependencies", ">up"),
    ("upgrade to the latest version of Python", ">up"),
    ("update the database driver", ">up"),
    ("bump the package version", ">up"),
    ("upgrade the TypeScript compiler", ">up"),
    ("update the Docker base image", ">up"),
    ("update to the latest framework version", ">up"),

    //     25. Rename / Move (10)                                              
    ("rename the function getUserById to fetchUser", "~"),
    ("rename the file utils.js to helpers.js", ">mv"),
    ("move the file from src to lib", ">mv"),
    ("rename the class UserController to AccountController", ">mv"),
    ("move the function to a separate module", ">mv"),
    ("rename the variable temp to temperature", ">mv"),
    ("rename the method processData to transformData", "~"),
    ("move the configuration files to the config directory", ">mv"),
    ("rename the endpoint from /users to /accounts", ">mv"),
    ("move the tests to the __tests__ directory", ">mv"),

    //     26. Benchmark / Profile (10)                                        
    ("benchmark the API response time", ">bench"),
    ("profile the database query performance", ">bench"),
    ("measure the performance of the sorting algorithm", ">bench"),
    ("load test the authentication endpoint", ">bench"),
    ("stress test the WebSocket server", ">bench"),
    ("benchmark the serialization performance", ">bench"),
    ("profile the memory usage", ">bench"),
    ("measure the latency of the cache lookups", ">bench"),
    ("load test the file upload endpoint", ">bench"),
    ("benchmark the search query speed", ">bench"),

    //     27. Lint / Format (10)                                              
    ("lint the code in the API module", ">lint"),
    ("format the codebase", ">lint"),
    ("run the linter on the test files", ">lint"),
    ("auto format the source code", ">lint"),
    ("lint the TypeScript files", ">lint"),
    ("format the configuration files", ">lint"),
    ("run formatter on the stylesheets", ">lint"),
    ("lint", ">lint"),
    ("format the Go source files", ">lint"),
    ("run linter", ">lint"),

    //     28. Logging / Observability (10)                                    
    ("add logging to the payment service", ">log"),
    ("add logs to the authentication flow", ">log"),
    ("instrument the API endpoints", ">log"),
    ("add tracing to the request pipeline", ">log"),
    ("add metrics to the database queries", ">log"),
    ("add observability to the worker processes", ">log"),
    ("add logging for the error paths", ">log"),
    ("add logs for debugging the cache misses", ">log"),
    ("add tracing for the distributed system", ">log"),
    ("add metrics for the queue processing", ">log"),

    //     29. CI/CD (10)                                                      
    ("set up ci for the project", ">ci"),
    ("create a ci pipeline for the frontend", ">ci"),
    ("add a ci step for running the linter", ">ci"),
    ("configure ci for the monorepo", ">ci"),
    ("create a github action for running tests", ">ci"),
    ("set up cd for automatic deployments", ">ci"),
    ("add a github actions workflow for building the Docker image", ">ci"),
    ("create a ci cd pipeline for the backend", ">ci"),
    ("configure the pipeline for automated testing", ">ci"),
    ("add a ci job for security scanning", ">ci"),

    //     30. Merge (5)                                                       
    ("merge the feature branch into main", ">merge"),
    ("merge the pull request", ">merge"),
    ("squash and merge the bug fix branch", ">merge"),
    ("merge into the release branch", ">merge"),
    ("rebase and merge the feature PR", ">merge"),

    //     31. Type Annotations (5)                                            
    ("add type annotations to the utility functions", ">type"),
    ("add types for the API response objects", ">type"),
    ("type check the codebase", ">type"),
    ("add typing to the configuration module", ">type"),
    ("add types to the event handlers", ">type"),

    //     32. Explain (15)                                                    
    ("explain how the authentication flow works", ">explain"),
    ("explain the code in the payment module", ">explain"),
    ("describe how the caching system works", ">explain"),
    ("walk me through the deployment pipeline", ">explain"),
    ("explain how to configure the database", ">explain"),
    ("explain why the tests are structured this way", ">explain"),
    ("describe the architecture of the system", ">explain"),
    ("explain what the middleware does", ">explain"),
    ("walk through the request lifecycle", ">explain"),
    ("explain how the event system processes messages", ">explain"),
    ("describe how the search indexing works", ">explain"),
    ("explain the error handling strategy", ">explain"),
    ("walk me through the data migration process", ">explain"),
    ("explain how the CI pipeline works", ">explain"),
    ("describe how the load balancer distributes traffic", ">explain"),

    //     33. Noise-heavy variations (20)                                     
    ("could you please implement user authentication", ">impl"),
    ("can you please fix the bug in the login flow", ">fix"),
    ("would you please write tests for the payment module", ">test"),
    ("i need you to create documentation for the API", ">doc"),
    ("i want you to refactor the user service", ">ref"),
    ("i'd like you to review the code in the auth module", ">rev"),
    ("help me implement caching", ">impl"),
    ("can you help me debug the memory leak", ">fix"),
    ("please optimize the database queries", ">opt"),
    ("i need to deploy the application to production", ">dep"),
    ("i want to add support for webhooks", ">add"),
    ("i'd like to migrate from MySQL to PostgreSQL", ">mig"),
    ("could you configure the logging framework", ">cfg"),
    ("can you add error handling to the API", ">err"),
    ("would you create a CI pipeline for the project", ">ci"),
    ("please benchmark the API performance", ">bench"),
    ("i need you to add types to the utility functions", ">type"),
    ("help me to explain how the caching works", ">explain"),
    ("please plan the implementation of the new feature", ">plan"),
    ("i want you to security audit of the authentication", ">sec"),

    //     34. Structural: Add field/method/param (25)                         
    ("add a field called email to the User struct", "@user+."),
    ("add a field name to the Customer class", "@customer+."),
    ("add a property age to the Person struct", "@person+."),
    ("add field status to the Order", "@order+."),
    ("add a member count to the Counter", "@counter+."),
    ("add a method validate to the Order class", "@order+~"),
    ("add a method serialize to the User struct", "@user+~"),
    ("add a function process to the Worker class", "@worker+~"),
    ("add method handle to the EventEmitter", "@eventemitter+~"),
    ("add a parameter timeout to the connect function", "~connect+$"),
    ("add a parameter retries to the fetch function", "~fetch+$"),
    ("add an argument callback to the subscribe function", "~subscribe+$"),
    ("add a constructor to the User class", "@user+~new"),
    ("add a getter for name on the User struct", "@user+~get."),
    ("add a setter for email on the Account class", "@account+~set."),
    ("add a variant Pending to the Status enum", "@status+."),
    ("add a variant Error to the Result enum", "@result+."),
    ("add a field description to the Product", "@product+."),
    ("add a method toString to the Config class", "@config+~"),
    ("add a parameter options to the initialize function", "~initialize+$"),
    ("create a field apiKey on the Settings struct", "@settings+."),
    ("add a method clone to the Document class", "@document+~"),
    ("add a field createdAt to the Record struct", "@record+."),
    ("add a parameter logger to the setup function", "~setup+$"),
    ("add a variant Timeout to the Error enum", "@error+."),

    //     35. Structural: Remove field/method/param (15)                      
    ("remove the field email from the User struct", "@user-."),
    ("remove the field age from the Person class", "@person-."),
    ("delete the field status from the Order", "@order-."),
    ("remove the method validate from the Order class", "@order-~"),
    ("remove the method serialize from the Config", "@config-~"),
    ("delete the method cleanup from the Worker", "@worker-~"),
    ("remove the parameter timeout from the connect function", "~connect-$"),
    ("remove the parameter callback from the subscribe function", "~subscribe-$"),
    ("drop the field deprecated from the Settings struct", "@settings-."),
    ("remove the method legacy from the API class", "@api-~"),
    ("remove field temp from the Cache struct", "@cache-."),
    ("delete the parameter debug from the init function", "~init-$"),
    ("remove the variant Unused from the Status enum", "@status-."),
    ("remove the field metadata from the Event", "@event-."),
    ("remove the method reset from the Counter class", "@counter-~"),

    //     36. Structural: Rename field/method (10)                            
    ("rename the field name to fullName on the User struct", "@user."),
    ("rename the field email to contactEmail on the Account class", "@account."),
    ("rename the method process to handle in the Worker class", "@worker~"),
    ("rename the method getData to fetchData in the API", "@api~"),
    ("rename field status to state in the Order struct", "@order."),
    ("rename method init to initialize in the Service class", "@service~"),
    ("rename the field url to endpoint on the Config struct", "@config."),
    ("rename the method run to execute in the Task class", "@task~"),
    ("rename the parameter name to label in the render function", "@render$"),
    ("rename field count to total on the Summary struct", "@summary."),

    //     37. Structural: Update/set field value (10)                         
    ("update the status field on the Order struct to shipped", "@order.status=$"),
    ("set the name field on the User to admin", "@user.name=$"),
    ("change the value of count in the Counter to 0", "@counter.count=$"),
    ("update the priority field on the Task to high", "@task.priority=$"),
    ("set the enabled field on the Feature to true", "@feature.enabled=$"),
    ("update the version field on the Package to 2", "@package.version=$"),
    ("set the timeout field on the Config to 30", "@config.timeout=$"),
    ("change the value of retries in the Settings to 3", "@settings.retries=$"),
    ("update the role field on the User to admin", "@user.role=$"),
    ("set the status field on the Build to success", "@build.status=$"),

    //     38. Structural: Change type (10)                                    
    ("change the type of the name field on User to string", "@user.name:"),
    ("change the type of the age field on Person to u32", "@person.age:"),
    ("change the type of field email on Account to Email", "@account."),
    ("change the type of the status field on Order to StatusEnum", "@order."),
    ("change the type of the count field on Counter from i32 to u64", "@counter.count:"),
    ("change the data type of the id field on Record to uuid", "@record."),
    ("change the type of the score field on Player to f64", "@player."),
    ("change the type of the payload field on Message to bytes", "@message."),
    ("change the type of the config field on App to AppConfig", "@app."),
    ("change the type of the handler field on Router to HandlerFn", "@router."),

    //     39. Structural: Change return type (5)                              
    ("change the return type of the process function to Result", "~process"),
    ("change the return type of validate to bool", "~validate"),
    ("change the return type of the fetch function to Response", "~fetch"),
    ("set the return type of the parse function to AST", "~parse"),
    ("change the return type of the serialize method to string", "~serialize"),

    //     40. Structural: Make modifier (15)                                   
    ("make the name field on User public", "@user.name+pub"),
    ("make the email field on Account private", "@account.email+priv"),
    ("make the process method async", "~process+async"),
    ("make the handler static", "@handler+static"),
    ("make the User class abstract", "@user+abstract"),
    ("make the Config struct immutable", "@config+immut"),
    ("make the count field on Counter mutable", "@counter.count+mut"),
    ("make the id field on Record readonly", "@record.id+readonly"),
    ("make the validate method public", "~validate+pub"),
    ("make the Service class final", "@service+final"),
    ("make the helper function pure", "~helper+pure"),
    ("make the cache field on App optional", "@app.cache+opt"),
    ("make the Handler exported", "@handler+export"),
    ("make the data field on Packet const", "@packet.data+const"),
    ("make the cleanup method deprecated", "~cleanup+depr"),

    //     41. Structural: Implement/Extend (10)
    ("implement the Serializable interface on the User struct", "@user:impl(@serializable)"),
    ("implement the Display trait on the Config struct", "@config:impl(@display)"),
    ("implement the Comparable interface on the Product class", "@product:impl(@comparable)"),
    ("have User implement Clone", "@user:impl(@clone)"),
    ("have Order implement Serializable", "@order:impl(@serializable)"),
    ("extend the BaseController with UserController", "@usercontroller<@basecontroller"),
    ("extend the AbstractService with PaymentService", "@paymentservice<@abstractservice"),
    ("have AdminUser extend User", "@adminuser<@user"),
    ("have PremiumAccount extend Account", "@premiumaccount<@account"),
    ("make the Worker implement Runnable", "@worker:impl(@runnable)"),

    //     42. Structural: Import operations (10)
    ("add an import for React", "+use(react)"),
    ("add an import for the lodash module", "+use(lodash)"),
    ("import the axios module", "+use(axios)"),
    ("add import for numpy", "+use(numpy)"),
    ("import express", "+use(express)"),
    ("remove the import for lodash", "-use(lodash)"),
    ("remove import for moment", "-use(moment)"),
    ("remove the import for underscore", "-use(underscore)"),
    ("add an import for the fs module", "+use(fs)"),
    ("add import for serde", "+use(serde)"),
];

#[test]
fn test_all_500_questions() {
    let ct = CodeTranslator::new();
    let mut failures: Vec<(usize, &str, &str, String)> = Vec::new();

    for (i, (input, expected_prefix)) in TEST_CASES.iter().enumerate() {
        let result = ct.translate(input);
        if !result.matched {
            failures.push((i + 1, input, expected_prefix, "NOT MATCHED".to_string()));
        } else if !result.axon.starts_with(expected_prefix) {
            failures.push((i + 1, input, expected_prefix, result.axon.clone()));
        }
    }

    if !failures.is_empty() {
        let mut msg = format!("\n{} of {} test cases failed:\n\n", failures.len(), TEST_CASES.len());
        for (num, input, expected, actual) in &failures {
            msg.push_str(&format!(
                "  #{}: {:?}\n    expected prefix: {:?}\n    got: {:?}\n\n",
                num, input, expected, actual
            ));
        }
        panic!("{}", msg);
    }

    assert!(TEST_CASES.len() >= 500, "Expected at least 500 test cases, got {}", TEST_CASES.len());
}

#[test]
fn test_token_savings_across_all() {
    let ct = CodeTranslator::new();
    let mut total_input_tokens = 0usize;
    let mut total_output_tokens = 0usize;
    let mut matched = 0usize;

    for (input, _) in TEST_CASES {
        let result = ct.translate(input);
        if result.matched {
            matched += 1;
            total_input_tokens += input.split_whitespace().count();
            total_output_tokens += result.axon.split_whitespace().count();
        }
    }

    let savings_pct = if total_input_tokens > 0 {
        ((total_input_tokens - total_output_tokens) as f64 / total_input_tokens as f64) * 100.0
    } else {
        0.0
    };

    eprintln!("\n=== Token Savings Report ===");
    eprintln!("Matched: {}/{}", matched, TEST_CASES.len());
    eprintln!("Total input tokens:  {}", total_input_tokens);
    eprintln!("Total output tokens: {}", total_output_tokens);
    eprintln!("Average savings:     {:.1}%", savings_pct);
    eprintln!("============================\n");

    // We expect at least 50% average savings across all questions
    assert!(savings_pct > 50.0, "Expected >50% savings, got {:.1}%", savings_pct);
}
